security:
    password_hashers:
        App\Entity\Utilisateurs:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
            logout:
                path: app_logout
                target: app_login
            custom_authenticator: App\Security\LoginAuthenticator
            entry_point: form_login
 
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/prelevement, roles: ROLE_USER }

